name: devopsdaysmad-inspec-azure-platform
title: Azure InSpec Profile
maintainer: Alejandro garcia
copyright: The Authors
copyright_email: agarciamiravet@gmail.com
license: Apache-2.0
summary: An InSpec Compliance Profile For Azure
version: 0.1.0
inspec_version: '>= 2.2.7'
depends:
  - name: inspec-azure
    git: https://github.com/agarciamiravet/inspec-azure.git
    branch: feature-storageaccountslist
supports:
- platform: azure